#!/bin/bash

# Thoroughly remove the StorageOS plugin.

set -e -u

echo "Unconditionally removing storageos plugin"
docker plugin rm -f storageos || true

# Ideally this would not be necessary.
echo "Restarting Docker host"
rc-service -q docker restart
