#!/bin/bash

set -e

# Install tools for sepc tests.
if [ ! -f /usr/bin/jq ]; then
  apk add jq
fi
if [ ! -f /usr/bin/http ]; then
  apk add python py-pip
  pip install --upgrade --disable-pip-version-check httpie
fi
