#!/bin/bash

set -e

# num_nodes=1

# hostname=$(hostname)
apk add perl
default_int=$(ip -4 route list 0/0 | perl -ne 'print "$1\n" if m/dev (\w+)\s*/;')
ip=$(ip -4 a show dev "$default_int" | perl -ne 'print "$1\n" if m!^\s+inet ([^/]+)/(\d+) (?:brd|scope)!;')
# ip=$(getent hosts "${hostname}.local" | awk '{print $1}')

echo "Starting consul on $ip"
docker rm -f consul || true
docker pull consul | cat
docker run -d --name consul --net=host consul agent \
    -server \
    -bind="${ip}" \
    -client=0.0.0.0 \
    -bootstrap-expect=1
sleep 1
echo "Querying local consul agent"
docker exec consul consul info | egrep 'version ='
