#!/bin/bash

set -e

if [ -z "$1" ]; then
	version=0.7.6
else
	version="$1"
	shift
fi

plugin=storageos/plugin
ip=$(avahi-resolve-host-name -4 "$(hostname -s).local" | cut -f2)

# Don't recreate dir if it exists.  Consul will still have old id registered so
# it needs to re-use same config for each run.
# shellcheck disable=SC2043
for dir in /var/lib/storageos; do
  [ -d $dir ] || mkdir -p $dir
done

# TODO: Move this to controlplane startup
modprobe nbd nbds_max=1024 max_part=15
modprobe fuse

echo "starting storageos plugin on $ip"
docker plugin rm -f storageos 2>/dev/null || true
docker plugin install --alias storageos --grant-all-permissions "$plugin:$version" ADVERTISE_IP="${ip}" KV_ADDR="${ip}"
