#!/bin/bash

set -e

cluster_hostnames=("$@")
num_nodes=${#cluster_hostnames[@]}

ip=$(avahi-resolve-host-name -4 "$(hostname -s).local" | cut -f2)
leader_ip=$(avahi-resolve-host-name -4 "${cluster_hostnames[0]}.local" | cut -f2)

echo "Starting consul on $ip with $num_nodes nodes, leader on $leader_ip"
docker rm -f consul 2>&1 || true
docker pull consul |cat
docker run -d --name consul --net=host consul agent -server \
-bind="${ip}" \
-client=0.0.0.0 \
-bootstrap-expect="${num_nodes}" \
-retry-join="${leader_ip}"

sleep 2
echo "Querying local consul agent"
docker exec consul consul info | egrep 'version ='
docker exec consul consul info | egrep 'leader'
